version: "3.9"
services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map port 3000 in the container to port 3000 on your machine
    volumes:
      - .:/app # Mount the project directory to the container
      - /app/node_modules # Exclude node_modules from being overwritten
    stdin_open: true
    tty: true
